# Generated by Django 6.0.3 on 2026-05-21 14:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ESP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("hashcode", models.CharField(max_length=100, unique=True)),
                (
                    "device_code",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("esp_name", models.CharField(blank=True, max_length=100)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("firmware_version", models.CharField(blank=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UNCLAIMED", "Chưa gán"),
                            ("ONLINE", "Đang online"),
                            ("OFFLINE", "Đang offline"),
                            ("ERROR", "Lỗi"),
                        ],
                        default="UNCLAIMED",
                        max_length=20,
                    ),
                ),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "esps",
                "ordering": ["hashcode"],
            },
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to="smarthome.esp",
                    ),
                ),
            ],
            options={
                "db_table": "activity_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Home",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "homes",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="esp",
            name="home",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="esp_devices",
                to="smarthome.home",
            ),
        ),
        migrations.CreateModel(
            name="MQTTMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=255)),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("INBOUND", "ESP gửi lên Django"),
                            ("OUTBOUND", "Django gửi xuống ESP"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("SYN", "Ping online"),
                            ("ACK", "Xac nhan MQTT"),
                            ("SENSOR", "Dữ liệu cảm biến"),
                            ("STATE", "Trạng thái switch"),
                            ("SET", "Lệnh điều khiển"),
                            ("UNKNOWN", "Không xác định"),
                        ],
                        default="UNKNOWN",
                        max_length=20,
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("is_processed", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mqtt_messages",
                        to="smarthome.esp",
                    ),
                ),
            ],
            options={
                "db_table": "mqtt_messages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("floor", models.IntegerField(default=1)),
                ("description", models.TextField(blank=True)),
                (
                    "home",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="smarthome.home",
                    ),
                ),
            ],
            options={
                "db_table": "rooms",
                "ordering": ["home", "floor", "name"],
                "unique_together": {("home", "name")},
            },
        ),
        migrations.AddField(
            model_name="esp",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="esp_devices",
                to="smarthome.room",
            ),
        ),
        migrations.CreateModel(
            name="SensorReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("temperature", models.FloatField(blank=True, null=True)),
                ("humidity", models.FloatField(blank=True, null=True)),
                ("smoke_level", models.FloatField(blank=True, null=True)),
                ("is_smoke_detected", models.BooleanField(default=False)),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sensor_readings",
                        to="smarthome.esp",
                    ),
                ),
            ],
            options={
                "db_table": "sensor_readings",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("HIGH_TEMPERATURE", "Nhiệt độ cao"),
                            ("HIGH_HUMIDITY", "Độ ẩm cao"),
                            ("HIGH_SMOKE_LEVEL", "Mức khói cao"),
                            ("SMOKE_DETECTED", "Phát hiện khói"),
                            ("DEVICE_OFFLINE", "Thiết bị offline"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Thấp"),
                            ("MEDIUM", "Trung bình"),
                            ("HIGH", "Cao"),
                            ("CRITICAL", "Nghiêm trọng"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("threshold_value", models.FloatField(blank=True, null=True)),
                ("actual_value", models.FloatField(blank=True, null=True)),
                ("is_resolved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="smarthome.esp",
                    ),
                ),
                (
                    "sensor_reading",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alerts",
                        to="smarthome.sensorreading",
                    ),
                ),
            ],
            options={
                "db_table": "alerts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Switch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("switch_code", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                (
                    "desired_state",
                    models.CharField(
                        choices=[("ON", "Bật"), ("OFF", "Tắt")],
                        default="OFF",
                        max_length=10,
                    ),
                ),
                (
                    "actual_state",
                    models.CharField(
                        choices=[("ON", "Bật"), ("OFF", "Tắt")],
                        default="OFF",
                        max_length=10,
                    ),
                ),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("SYNCED", "Đã đồng bộ"),
                            ("PENDING", "Đang chờ ESP xác nhận"),
                            ("FAILED", "Đồng bộ thất bại"),
                        ],
                        default="SYNCED",
                        max_length=20,
                    ),
                ),
                ("last_controlled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "esp_device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="switches",
                        to="smarthome.esp",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="switches",
                        to="smarthome.room",
                    ),
                ),
            ],
            options={
                "db_table": "switches",
                "ordering": ["esp_device", "switch_code"],
            },
        ),
        migrations.CreateModel(
            name="DeviceCommand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "command_type",
                    models.CharField(default="SET_DEVICE_STATE", max_length=50),
                ),
                ("command_value", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Đang chờ xử lý"),
                            ("PUBLISHED", "Đã publish MQTT"),
                            ("DONE", "ESP đã thực hiện"),
                            ("FAILED", "Thất bại"),
                            ("TIMEOUT", "Quá thời gian phản hồi"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="device_commands",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "esp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commands",
                        to="smarthome.esp",
                    ),
                ),
                (
                    "switch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commands",
                        to="smarthome.switch",
                    ),
                ),
            ],
            options={
                "db_table": "device_commands",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="esp",
            index=models.Index(fields=["hashcode"], name="esps_hashcod_7f8f2a_idx"),
        ),
        migrations.AddIndex(
            model_name="esp",
            index=models.Index(fields=["status"], name="esps_status_228b13_idx"),
        ),
        migrations.AddIndex(
            model_name="esp",
            index=models.Index(
                fields=["home", "status"], name="esps_home_id_372272_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="switch",
            unique_together={("esp_device", "switch_code")},
        ),
    ]
