# Generated by Django 6.0.3 on 2026-05-20 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ESPDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hashcode", models.CharField(max_length=100, unique=True)),
                (
                    "device_code",
                    models.CharField(blank=True, max_length=100, unique=True),
                ),
                ("esp_name", models.CharField(blank=True, max_length=100)),
                ("api_key", models.CharField(blank=True, max_length=128)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("firmware_version", models.CharField(blank=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ONLINE", "ONLINE"),
                            ("OFFLINE", "OFFLINE"),
                            ("ERROR", "ERROR"),
                        ],
                        default="OFFLINE",
                        max_length=20,
                    ),
                ),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "esp_devices",
                "ordering": ["hashcode"],
            },
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to="smarthome.espdevice",
                    ),
                ),
            ],
            options={
                "db_table": "activity_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Home",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "homes",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="espdevice",
            name="home",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="esp_devices",
                to="smarthome.home",
            ),
        ),
        migrations.CreateModel(
            name="Light",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_code", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("gpio_pin", models.IntegerField(blank=True, null=True)),
                (
                    "desired_state",
                    models.CharField(
                        choices=[("ON", "ON"), ("OFF", "OFF")],
                        default="OFF",
                        max_length=10,
                    ),
                ),
                (
                    "actual_state",
                    models.CharField(
                        choices=[("ON", "ON"), ("OFF", "OFF")],
                        default="OFF",
                        max_length=10,
                    ),
                ),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("SYNCED", "SYNCED"),
                            ("PENDING", "PENDING"),
                            ("FAILED", "FAILED"),
                        ],
                        default="SYNCED",
                        max_length=20,
                    ),
                ),
                ("last_controlled_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lights",
                        to="smarthome.espdevice",
                    ),
                ),
            ],
            options={
                "db_table": "lights",
                "ordering": ["device", "device_code"],
            },
        ),
        migrations.CreateModel(
            name="DeviceCommand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "command_type",
                    models.CharField(default="SET_LIGHT_STATE", max_length=50),
                ),
                ("command_value", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("SENT", "SENT"),
                            ("DONE", "DONE"),
                            ("FAILED", "FAILED"),
                            ("EXPIRED", "EXPIRED"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="device_commands",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commands",
                        to="smarthome.espdevice",
                    ),
                ),
                (
                    "light",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commands",
                        to="smarthome.light",
                    ),
                ),
            ],
            options={
                "db_table": "device_commands",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("floor", models.IntegerField(default=1)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "home",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="smarthome.home",
                    ),
                ),
            ],
            options={
                "db_table": "rooms",
                "ordering": ["home", "floor", "name"],
                "unique_together": {("home", "name")},
            },
        ),
        migrations.AddField(
            model_name="light",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lights",
                to="smarthome.room",
            ),
        ),
        migrations.AddField(
            model_name="espdevice",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="esp_devices",
                to="smarthome.room",
            ),
        ),
        migrations.CreateModel(
            name="SensorReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("temperature", models.FloatField(default=0)),
                ("humidity", models.FloatField(default=0)),
                ("smoke_level", models.FloatField(default=0)),
                ("is_smoke_detected", models.BooleanField(default=False)),
                ("recorded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sensor_readings",
                        to="smarthome.espdevice",
                    ),
                ),
            ],
            options={
                "db_table": "sensor_readings",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alert_type", models.CharField(max_length=50)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "LOW"),
                            ("MEDIUM", "MEDIUM"),
                            ("HIGH", "HIGH"),
                            ("CRITICAL", "CRITICAL"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("threshold_value", models.FloatField(blank=True, null=True)),
                ("actual_value", models.FloatField(blank=True, null=True)),
                ("is_resolved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="smarthome.espdevice",
                    ),
                ),
                (
                    "sensor_reading",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alerts",
                        to="smarthome.sensorreading",
                    ),
                ),
            ],
            options={
                "db_table": "alerts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="light",
            unique_together={("device", "device_code")},
        ),
    ]
