# Generated by Django 6.0.3 on 2026-05-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smarthome", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="espdevice",
            name="device_code",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
