# Generated by Django 5.2.14 on 2026-05-20 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('floor', models.IntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='smarthome.home')),
            ],
            options={
                'ordering': ['home__name', 'floor', 'name'],
                'constraints': [models.UniqueConstraint(fields=('home', 'name'), name='unique_room_name_per_home')],
            },
        ),
    ]
