# Generated by Django 6.0.3 on 2026-05-24 11:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smarthome", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="esp",
            name="device_code",
        ),
        migrations.RemoveField(
            model_name="sensorreading",
            name="is_smoke_detected",
        ),
        migrations.RemoveField(
            model_name="switch",
            name="name",
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["user", "created_at"], name="activity_lo_user_id_d23b30_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["device", "created_at"], name="activity_lo_device__b85004_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(fields=["action"], name="activity_lo_action_b49f28_idx"),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["created_at"], name="activity_lo_created_166e11_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["device", "is_resolved"], name="alerts_device__ca48df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(fields=["alert_type"], name="alerts_alert_t_eda531_idx"),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(fields=["severity"], name="alerts_severit_362484_idx"),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["is_resolved"], name="alerts_is_reso_d52617_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(fields=["created_at"], name="alerts_created_965da5_idx"),
        ),
        migrations.AddIndex(
            model_name="devicecommand",
            index=models.Index(
                fields=["esp", "status"], name="device_comm_esp_id_ce2f48_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="devicecommand",
            index=models.Index(
                fields=["switch", "status"], name="device_comm_switch__21ba52_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="devicecommand",
            index=models.Index(
                fields=["created_by", "created_at"],
                name="device_comm_created_141fb5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="devicecommand",
            index=models.Index(
                fields=["status", "created_at"], name="device_comm_status_dc0b6c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="devicecommand",
            index=models.Index(
                fields=["published_at"], name="device_comm_publish_b106f4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="devicecommand",
            index=models.Index(
                fields=["acknowledged_at"], name="device_comm_acknowl_2c08db_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="esp",
            index=models.Index(
                fields=["room", "status"], name="esps_room_id_bcc8a3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="esp",
            index=models.Index(fields=["last_seen_at"], name="esps_last_se_808965_idx"),
        ),
        migrations.AddIndex(
            model_name="home",
            index=models.Index(
                fields=["owner", "name"], name="homes_owner_i_d7f523_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="home",
            index=models.Index(fields=["created_at"], name="homes_created_79fca4_idx"),
        ),
        migrations.AddIndex(
            model_name="mqttmessage",
            index=models.Index(
                fields=["device", "created_at"], name="mqtt_messag_device__0329e1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mqttmessage",
            index=models.Index(fields=["topic"], name="mqtt_messag_topic_b7b304_idx"),
        ),
        migrations.AddIndex(
            model_name="mqttmessage",
            index=models.Index(
                fields=["direction"], name="mqtt_messag_directi_c4c3c7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mqttmessage",
            index=models.Index(
                fields=["message_type"], name="mqtt_messag_message_9e34ba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mqttmessage",
            index=models.Index(
                fields=["is_processed"], name="mqtt_messag_is_proc_07dad6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mqttmessage",
            index=models.Index(
                fields=["created_at"], name="mqtt_messag_created_18b605_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(
                fields=["home", "floor", "name"], name="rooms_home_id_d18712_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(fields=["created_at"], name="rooms_created_3ab07f_idx"),
        ),
        migrations.AddIndex(
            model_name="sensorreading",
            index=models.Index(
                fields=["device", "recorded_at"], name="sensor_read_device__a116dc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sensorreading",
            index=models.Index(
                fields=["device", "created_at"], name="sensor_read_device__692b87_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sensorreading",
            index=models.Index(
                fields=["recorded_at"], name="sensor_read_recorde_199dde_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sensorreading",
            index=models.Index(
                fields=["created_at"], name="sensor_read_created_8a2007_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="switch",
            index=models.Index(
                fields=["esp_device", "switch_code"], name="switches_esp_dev_8d16ad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="switch",
            index=models.Index(
                fields=["room", "actual_state"], name="switches_room_id_11c66a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="switch",
            index=models.Index(
                fields=["sync_status"], name="switches_sync_st_dddfaa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="switch",
            index=models.Index(
                fields=["last_controlled_at"], name="switches_last_co_2cb55c_idx"
            ),
        ),
    ]
