# Generated by Django 6.0.3 on 2026-05-25 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smarthome", "0002_remove_esp_device_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="esp",
            name="is_sensor",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="esp",
            index=models.Index(fields=["is_sensor"], name="esps_is_sens_c3e9ed_idx"),
        ),
    ]
