# Generated by Django 5.2.14 on 2026-05-20 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthome', '0002_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_name', models.CharField(max_length=100)),
                ('hashcode', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('firmware_version', models.CharField(blank=True, max_length=50)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esp_devices', to='smarthome.home')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='esp_devices', to='smarthome.room')),
            ],
            options={
                'ordering': ['home__name', 'room__name', 'device_name'],
            },
        ),
    ]
