# Generated by Django 5.2.14 on 2026-05-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthome', '0003_espdevice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='espdevice',
            options={'ordering': ['device_name']},
        ),
        migrations.AddField(
            model_name='espdevice',
            name='device_secret',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='espdevice',
            name='mqtt_sensor_topic',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='espdevice',
            name='mqtt_set_topic',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='espdevice',
            name='mqtt_state_topic',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='espdevice',
            name='hashcode',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='espdevice',
            name='status',
            field=models.CharField(choices=[('UNCLAIMED', 'Chưa gán'), ('ONLINE', 'Đang online'), ('OFFLINE', 'Đang offline'), ('ERROR', 'Lỗi')], default='UNCLAIMED', max_length=20),
        ),
        migrations.AddIndex(
            model_name='espdevice',
            index=models.Index(fields=['hashcode'], name='smarthome_e_hashcod_9d7a32_idx'),
        ),
        migrations.AddIndex(
            model_name='espdevice',
            index=models.Index(fields=['status'], name='smarthome_e_status_4252c7_idx'),
        ),
        migrations.AddIndex(
            model_name='espdevice',
            index=models.Index(fields=['home', 'status'], name='smarthome_e_home_id_6493d8_idx'),
        ),
    ]
