# Generated by Django 6.0.3 on 2026-05-25 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smarthome", "0003_esp_is_sensor_esp_esps_is_sens_c3e9ed_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="switch",
            name="switch_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
