# Generated by Django 6.0.3 on 2026-05-25 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("smarthome", "0004_switch_switch_name"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="switch",
            name="switches_room_id_11c66a_idx",
        ),
        migrations.RemoveField(
            model_name="switch",
            name="room",
        ),
    ]
