# Generated by Django 5.2.14 on 2026-05-20 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthome', '0004_alter_espdevice_options_espdevice_device_secret_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('switch_code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('gpio_pin', models.IntegerField(blank=True, null=True)),
                ('desired_state', models.CharField(choices=[('ON', 'Bật'), ('OFF', 'Tắt')], default='OFF', max_length=10)),
                ('actual_state', models.CharField(choices=[('ON', 'Bật'), ('OFF', 'Tắt')], default='OFF', max_length=10)),
                ('sync_status', models.CharField(choices=[('SYNCED', 'Đã đồng bộ'), ('PENDING', 'Đang chờ ESP xác nhận'), ('FAILED', 'Đồng bộ thất bại')], default='SYNCED', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_controlled_at', models.DateTimeField(blank=True, null=True)),
                ('esp_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='switches', to='smarthome.espdevice')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='switches', to='smarthome.room')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['esp_device', 'switch_code'], name='smarthome_s_esp_dev_4b13b2_idx'), models.Index(fields=['sync_status'], name='smarthome_s_sync_st_8293ab_idx'), models.Index(fields=['is_active'], name='smarthome_s_is_acti_7002a4_idx')],
                'constraints': [models.UniqueConstraint(fields=('esp_device', 'switch_code'), name='unique_switch_code_per_esp')],
            },
        ),
    ]
