# Generated by Django 6.0.3 on 2026-05-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smarthome", "0005_align_current_smarthome_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="alert_type",
            field=models.CharField(
                choices=[
                    ("HIGH_TEMPERATURE", "Nhiệt độ cao"),
                    ("HIGH_HUMIDITY", "Độ ẩm cao"),
                    ("HIGH_SMOKE_LEVEL", "Mức khói cao"),
                    ("SMOKE_DETECTED", "Phát hiện khói"),
                    ("DEVICE_OFFLINE", "Thiết bị offline"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="alert",
            name="severity",
            field=models.CharField(
                choices=[
                    ("LOW", "Thấp"),
                    ("MEDIUM", "Trung bình"),
                    ("HIGH", "Cao"),
                    ("CRITICAL", "Nghiêm trọng"),
                ],
                default="MEDIUM",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="devicecommand",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Đang chờ xử lý"),
                    ("PUBLISHED", "Đã publish MQTT"),
                    ("DONE", "ESP đã thực hiện"),
                    ("FAILED", "Thất bại"),
                    ("TIMEOUT", "Quá thời gian phản hồi"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="esp",
            name="status",
            field=models.CharField(
                choices=[
                    ("UNCLAIMED", "Chưa gán"),
                    ("ONLINE", "Đang online"),
                    ("OFFLINE", "Đang offline"),
                    ("ERROR", "Lỗi"),
                ],
                default="UNCLAIMED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="mqttmessage",
            name="direction",
            field=models.CharField(
                choices=[
                    ("INBOUND", "ESP gửi lên Django"),
                    ("OUTBOUND", "Django gửi xuống ESP"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="mqttmessage",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("PING", "Ping online"),
                    ("ACK", "Xac nhan MQTT"),
                    ("SENSOR", "Dữ liệu cảm biến"),
                    ("STATE", "Trạng thái switch"),
                    ("SET", "Lệnh điều khiển"),
                    ("UNKNOWN", "Không xác định"),
                ],
                default="UNKNOWN",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="switch",
            name="actual_state",
            field=models.CharField(
                choices=[("ON", "Bật"), ("OFF", "Tắt")], default="OFF", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="switch",
            name="desired_state",
            field=models.CharField(
                choices=[("ON", "Bật"), ("OFF", "Tắt")], default="OFF", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="switch",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("SYNCED", "Đã đồng bộ"),
                    ("PENDING", "Đang chờ ESP xác nhận"),
                    ("FAILED", "Đồng bộ thất bại"),
                ],
                default="SYNCED",
                max_length=20,
            ),
        ),
    ]
