# Generated by Django 5.2.14 on 2026-05-20 10:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthome', '0005_switch'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('smoke_level', models.FloatField(blank=True, null=True)),
                ('is_smoke_detected', models.BooleanField(default=False)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_readings', to='smarthome.espdevice')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['device', 'recorded_at'], name='smarthome_s_device__984ea3_idx'), models.Index(fields=['recorded_at'], name='smarthome_s_recorde_cf1b43_idx'), models.Index(fields=['is_smoke_detected'], name='smarthome_s_is_smok_ede44d_idx')],
            },
        ),
    ]
