# Generated by Django 6.0.3 on 2026-05-28 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smarthome", "0006_rename_smoke_level_to_gas"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutomationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("HIGH_TEMPERATURE", "Nhiệt độ cao"),
                            ("HIGH_HUMIDITY", "Độ ẩm cao"),
                            ("HIGH_SMOKE_LEVEL", "Mức khói cao"),
                            ("SMOKE_DETECTED", "Phát hiện khói"),
                            ("DEVICE_OFFLINE", "Thiết bị offline"),
                        ],
                        max_length=50,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                (
                    "active_state",
                    models.CharField(
                        choices=[("ON", "Bật"), ("OFF", "Tắt")],
                        default="ON",
                        max_length=10,
                    ),
                ),
                (
                    "normal_state",
                    models.CharField(
                        choices=[("ON", "Bật"), ("OFF", "Tắt")],
                        default="OFF",
                        max_length=10,
                    ),
                ),
                ("last_triggered_at", models.DateTimeField(blank=True, null=True)),
                ("last_normalized_at", models.DateTimeField(blank=True, null=True)),
                (
                    "sensor_device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automation_sensor_rules",
                        to="smarthome.esp",
                    ),
                ),
                (
                    "target_switch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automation_target_rules",
                        to="smarthome.switch",
                    ),
                ),
            ],
            options={
                "db_table": "automation_rules",
                "ordering": ["sensor_device", "alert_type", "target_switch"],
                "indexes": [
                    models.Index(
                        fields=["sensor_device", "enabled"],
                        name="automation__sensor__c89bc0_idx",
                    ),
                    models.Index(
                        fields=["target_switch", "enabled"],
                        name="automation__target__73c975_idx",
                    ),
                    models.Index(
                        fields=["alert_type", "enabled"],
                        name="automation__alert_t_5075d0_idx",
                    ),
                ],
                "unique_together": {("sensor_device", "alert_type", "target_switch")},
            },
        ),
    ]
