# Generated by Django 5.2.14 on 2026-05-20 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthome', '0006_sensorreading'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_type', models.CharField(choices=[('SET_SWITCH_STATE', 'Đặt trạng thái switch')], default='SET_SWITCH_STATE', max_length=50)),
                ('command_value', models.CharField(choices=[('ON', 'Bật'), ('OFF', 'Tắt')], max_length=10)),
                ('mqtt_topic', models.CharField(blank=True, max_length=150)),
                ('mqtt_payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Đang chờ xử lý'), ('PUBLISHED', 'Đã publish MQTT'), ('DONE', 'ESP đã thực hiện'), ('FAILED', 'Thất bại'), ('TIMEOUT', 'Quá thời gian phản hồi')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_commands', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='smarthome.espdevice')),
                ('switch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='smarthome.switch')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['device', 'status'], name='smarthome_d_device__16e309_idx'), models.Index(fields=['switch', 'status'], name='smarthome_d_switch__b3742c_idx'), models.Index(fields=['status'], name='smarthome_d_status_54c7fc_idx'), models.Index(fields=['created_at'], name='smarthome_d_created_aa8196_idx')],
            },
        ),
    ]
