# Generated by Django 6.0.3 on 2026-05-28 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("smarthome", "0007_automationrule"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="activitylog",
            name="activity_lo_user_id_d23b30_idx",
        ),
        migrations.RemoveIndex(
            model_name="activitylog",
            name="activity_lo_device__b85004_idx",
        ),
        migrations.RemoveIndex(
            model_name="activitylog",
            name="activity_lo_action_b49f28_idx",
        ),
        migrations.RemoveIndex(
            model_name="activitylog",
            name="activity_lo_created_166e11_idx",
        ),
        migrations.DeleteModel(
            name="ActivityLog",
        ),
    ]
