# Generated by Django 5.2.14 on 2026-05-20 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthome', '0007_devicecommand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('HIGH_TEMPERATURE', 'Nhiệt độ cao'), ('HIGH_HUMIDITY', 'Độ ẩm cao'), ('HIGH_SMOKE_LEVEL', 'Mức khói cao'), ('SMOKE_DETECTED', 'Phát hiện khói'), ('DEVICE_OFFLINE', 'Thiết bị offline')], max_length=50)),
                ('severity', models.CharField(choices=[('LOW', 'Thấp'), ('MEDIUM', 'Trung bình'), ('HIGH', 'Cao'), ('CRITICAL', 'Nghiêm trọng')], default='MEDIUM', max_length=20)),
                ('message', models.TextField()),
                ('threshold_value', models.FloatField(blank=True, null=True)),
                ('actual_value', models.FloatField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='smarthome.espdevice')),
                ('sensor_reading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='smarthome.sensorreading')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['device', 'is_resolved'], name='smarthome_a_device__489a1f_idx'), models.Index(fields=['alert_type'], name='smarthome_a_alert_t_5f0a3e_idx'), models.Index(fields=['severity'], name='smarthome_a_severit_735b7c_idx'), models.Index(fields=['is_resolved'], name='smarthome_a_is_reso_002529_idx'), models.Index(fields=['created_at'], name='smarthome_a_created_dac45a_idx')],
            },
        ),
    ]
