# Generated by Django 5.2.14 on 2026-05-20 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthome', '0008_alert'),
    ]

    operations = [
        migrations.CreateModel(
            name='MqttMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('direction', models.CharField(choices=[('INBOUND', 'ESP gửi lên Django'), ('OUTBOUND', 'Django gửi xuống ESP')], max_length=20)),
                ('message_type', models.CharField(choices=[('PING', 'Ping online'), ('SENSOR', 'Dữ liệu cảm biến'), ('STATE', 'Trạng thái switch'), ('SET', 'Lệnh điều khiển'), ('UNKNOWN', 'Không xác định')], default='UNKNOWN', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('is_processed', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mqtt_messages', to='smarthome.espdevice')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['device', 'created_at'], name='smarthome_m_device__ad692e_idx'), models.Index(fields=['topic'], name='smarthome_m_topic_b7d1c0_idx'), models.Index(fields=['direction'], name='smarthome_m_directi_a3bd58_idx'), models.Index(fields=['message_type'], name='smarthome_m_message_99d653_idx'), models.Index(fields=['is_processed'], name='smarthome_m_is_proc_bc1287_idx'), models.Index(fields=['created_at'], name='smarthome_m_created_a4c66c_idx')],
            },
        ),
    ]
