# Generated by Django 5.2.14 on 2026-05-20 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthome', '0009_mqttmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('USER_ACTION', 'Thao tác người dùng'), ('SWITCH_CONTROL', 'Điều khiển switch'), ('DEVICE_ONLINE', 'Thiết bị online'), ('DEVICE_OFFLINE', 'Thiết bị offline'), ('SENSOR_READING', 'Nhận dữ liệu cảm biến'), ('ALERT_CREATED', 'Tạo cảnh báo'), ('ALERT_RESOLVED', 'Xử lý cảnh báo'), ('MQTT_MESSAGE', 'Xử lý MQTT message'), ('SYSTEM', 'Hệ thống')], max_length=50)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='smarthome.espdevice')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='smarthome_a_user_id_1d9eb8_idx'), models.Index(fields=['device', 'created_at'], name='smarthome_a_device__e5c3ca_idx'), models.Index(fields=['action'], name='smarthome_a_action_29bfa1_idx'), models.Index(fields=['created_at'], name='smarthome_a_created_e35af4_idx')],
            },
        ),
    ]
