# Generated by Django 6.0.3 on 2026-05-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MQTTMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=255)),
                (
                    "direction",
                    models.CharField(
                        choices=[("INBOUND", "INBOUND"), ("OUTBOUND", "OUTBOUND")],
                        max_length=20,
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("SYN", "SYN"),
                            ("ACK", "ACK"),
                            ("SENSOR", "SENSOR"),
                            ("STATE", "STATE"),
                            ("SET", "SET"),
                            ("UNKNOWN", "UNKNOWN"),
                        ],
                        default="UNKNOWN",
                        max_length=20,
                    ),
                ),
                (
                    "device_hashcode",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("is_processed", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "mqtt_messages",
                "ordering": ["-created_at"],
            },
        ),
    ]
